# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: urlhs

before:
  hooks:
    - go mod tidy

builds:
  - id: urlhs
    main: .
    binary: urlhs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"

homebrew_casks:
  - name: urlhs
    repository:
      owner: andpalmier
      name: homebrew-tap
    homepage: "https://github.com/andpalmier/urlhs"
    description: "CLI tool to search in URLhaus database and submit URLs"
    directory: Casks
    url:
      verified: github.com/andpalmier/urlhs
    binaries:
      - urlhs
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/urlhs"]
          end

dockers:
  - image_templates:
      - "ghcr.io/andpalmier/urlhs:{{ .Version }}-amd64"
      - "ghcr.io/andpalmier/urlhs:latest-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
    ids:
      - urlhs
    extra_files: []
  - image_templates:
      - "ghcr.io/andpalmier/urlhs:{{ .Version }}-arm64"
      - "ghcr.io/andpalmier/urlhs:latest-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
    ids:
      - urlhs
    extra_files: []

docker_manifests:
  - name_template: "ghcr.io/andpalmier/urlhs:{{ .Version }}"
    image_templates:
      - "ghcr.io/andpalmier/urlhs:{{ .Version }}-amd64"
      - "ghcr.io/andpalmier/urlhs:{{ .Version }}-arm64"
  - name_template: "ghcr.io/andpalmier/urlhs:latest"
    image_templates:
      - "ghcr.io/andpalmier/urlhs:latest-amd64"
      - "ghcr.io/andpalmier/urlhs:latest-arm64"

release:
  github:
    owner: andpalmier
    name: urlhs
  draft: false
  prerelease: auto
